name: Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set tags
        id: vars
        run: echo "TAG=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/singsub:${{ env.TAG }}
            ghcr.io/${{ github.actor }}/singsub:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/singsub:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/singsub:latest
